language: node_js
node_js:
  - "4"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    recipients:
      - imansedighi@outlook.com
    on_success: change
    on_failure: always